require("config.globals")
require("config.options")
require("config.keymap")
require("config.autocmd")
require("config.colorscheme")

require("plugins.nvim-treesitter")
require("plugins.mini")
require("plugins.mini-pick")
require("plugins.indent-blankline")
require("plugins.conform")
require("plugins.mini-clue")
require("plugins.gitsigns")
require("plugins.nvim-dev-icons")
require("plugins.floating-term")
require("plugins.persistence")
require("plugins.render-markdown")
require("plugins.dressing")
require("plugins.mason")
require("plugins.opencode")

-- lsp requires copletion tool
require("plugins.mini-completion")
require("config.lsp")
